# mailpopbox
# Copyright 2025 Blue Static <https://www.bluestatic.org>
# This program is free software licensed under the GNU General Public License,
# version 3.0. The full text of the license can be found in LICENSE.txt.
# SPDX-License-Identifier: GPL-3.0-only

FROM golang:1.24-alpine

WORKDIR /go/src/mailpopbox
COPY . .

RUN go install -v ./...

EXPOSE 80/tcp

CMD ["/go/bin/mailpopbox-router", "/var/mailpopbox/router.json"]
